// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdvHs2w0BkUqA-Eys1ZZrh-2zCx4VCOjs',
    appId: '1:7346651866:web:d16013a2077607cf7edbe3',
    messagingSenderId: '7346651866',
    projectId: 'lipamusic-eb798',
    authDomain: 'lipamusic-eb798.firebaseapp.com',
    storageBucket: 'lipamusic-eb798.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD0IjeiHX5r1ESyIMdUuX-29aCoHbH4g4',
    appId: '1:7346651866:android:f1ab7453be6cace67edbe3',
    messagingSenderId: '7346651866',
    projectId: 'lipamusic-eb798',
    storageBucket: 'lipamusic-eb798.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH23mNtE0pJlvxq4l0hrtevcILuXB0Yg4',
    appId: '1:7346651866:ios:8ce9bfac348884e37edbe3',
    messagingSenderId: '7346651866',
    projectId: 'lipamusic-eb798',
    storageBucket: 'lipamusic-eb798.appspot.com',
    iosClientId: '7346651866-cema5aep80uibivl92usoq74896kpet9.apps.googleusercontent.com',
    iosBundleId: 'com.example.lipaMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH23mNtE0pJlvxq4l0hrtevcILuXB0Yg4',
    appId: '1:7346651866:ios:8ce9bfac348884e37edbe3',
    messagingSenderId: '7346651866',
    projectId: 'lipamusic-eb798',
    storageBucket: 'lipamusic-eb798.appspot.com',
    iosClientId: '7346651866-cema5aep80uibivl92usoq74896kpet9.apps.googleusercontent.com',
    iosBundleId: 'com.example.lipaMusic',
  );
}
